language: python
python:
  - "2.6"
  

before_script: mkdir -p shippable/codecoverage shippable/testresults
install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install -r tests/requirements.txt --use-mirrors
script: 
  - flake8 --ignore=F401 twilio
  - flake8 --ignore=E123,E126,E128,E501 tests
  - nosetests tests/  --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  - coverage run --branch tests/
  - coverage xml -o shippable/codecoverage/coverage.xml tests/
